# Generated by Django 6.0.3 on 2026-03-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
